format = "$directory$git_status$git_state$git_branch$character"

add_newline = false

[character]
success_symbol = "[➜](bold green)"
error_symbol =  "[➜](bold red)"
format = "[$symbol ](bold green)"

[directory]
truncation_length = 1

[git_branch]
format = '[\($branch\) ]($style)'
symbol = '󰊢 '
style = 'bold purple'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = 'blue'
staged = '[+](bold green)'
ahead = '[⇡](bold purple)'
untracked = '[?](bold blue)'
modified = '[!](bold yellow)'
deleted = '[✘](bold red)'
