format = """
$directory\
$git_branch\
$git_status\
$character\
"""

add_newline = false

[character]
success_symbol = "[➜](bold green)"
format = "[$symbol ](bold green)"

[directory]
truncation_length = 1

[git_branch]
format = '[\($branch\) ]($style)'
symbol = '󰊢 '
style = 'bold purple'

[git_status]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
disabled = true
